<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Entrar</name>
   <tag></tag>
   <elementGuidId>3f4acd0a-b967-4761-8a55-4b138e59f7d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-block.btn-lg.btn_orange</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='login-form']/div/form/div/div/div/div[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a274f775-743a-412a-8f6b-c9436529ae3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-block btn-lg btn_orange</value>
      <webElementGuid>a2eb6450-c517-478a-9209-48f2208ed475</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>validateLogin();</value>
      <webElementGuid>cb4e89eb-6468-4e2f-9b61-5af5ba9cd91a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Entrar</value>
      <webElementGuid>6a9d5cd0-2be6-44fc-be03-f4171debfe4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login-form&quot;)/div[@class=&quot;middle-cont&quot;]/form[@class=&quot;container-fluid ng-valid-maxlength ng-valid ng-valid-required ng-dirty ng-valid-correo-no-valido ng-valid-parse&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-6 ladoIzquierdo&quot;]/div[@class=&quot;login_cont&quot;]/div[@class=&quot;form-group&quot;]/a[@class=&quot;btn btn-block btn-lg btn_orange&quot;]</value>
      <webElementGuid>659723ee-1d36-4bac-931e-deba11611d12</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='login-form']/div/form/div/div/div/div[3]/a</value>
      <webElementGuid>e56d0aa5-42c4-45e8-96dd-2ee89ccb9ef8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Entrar')]</value>
      <webElementGuid>058daad3-50bb-4ce3-8371-2a29c2176101</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¿Olvidaste tu Contraseña?'])[1]/following::a[1]</value>
      <webElementGuid>106af222-dccb-49a2-a40c-7dd94f2d3b05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LaComer| Login'])[1]/following::a[4]</value>
      <webElementGuid>2e7f5336-5f5e-45ad-aa60-d4695f087561</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Regístrate'])[1]/preceding::a[1]</value>
      <webElementGuid>1e0bc8c8-e9c7-4383-9c30-9b3d81c6427d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Regístrate'])[2]/preceding::a[1]</value>
      <webElementGuid>15f34ff6-884e-4dc3-a929-811411ea4104</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Entrar']/parent::*</value>
      <webElementGuid>c3ecc9eb-9ebc-4995-bbc6-fe243a095dab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a</value>
      <webElementGuid>92e68edc-3a7e-49fa-b4cd-25da6e417a04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Entrar' or . = 'Entrar')]</value>
      <webElementGuid>3d1cdff7-54d4-439d-9739-59f43091aa8a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
