<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Piezas_addShopCartDetail</name>
   <tag></tag>
   <elementGuidId>7780eee5-ef87-4549-9013-f7e0a603ca5a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#addShopCartDetail</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='addShopCartDetail']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e68113d6-8c43-4003-899f-13c2f74bd8f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addShopCartDetail</value>
      <webElementGuid>33bfb90b-d1e0-4f1d-8b76-7bd74d64d781</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>aac107c6-9368-418f-afda-6fe37298ca9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default pd-btn-shopping-cart pd-btn-green ng-scope</value>
      <webElementGuid>5f959bb0-3884-4324-b14c-9f197766b033</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tooltip</value>
      <webElementGuid>11ac71a0-c169-43ac-a432-566d68b2116b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Agregar a carrito</value>
      <webElementGuid>9aaf120f-4dd9-4d64-b4d7-b0b5bf0c93d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>document.getElementById('boton').value = 1;</value>
      <webElementGuid>1d8007a7-8127-4be7-b24f-85f925c72d15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>!sac.isArtResurtido</value>
      <webElementGuid>feee23eb-5b8b-4398-a5d6-1ee05056bd4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>AgregarCarritoFromDetalle();</value>
      <webElementGuid>9500f300-bc02-4c83-bbe2-82269343bfe2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addShopCartDetail&quot;)</value>
      <webElementGuid>32270e8f-b52c-4627-b8b7-e22e15f2d591</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='addShopCartDetail']</value>
      <webElementGuid>bcb32aa9-5c8b-4895-911f-5c9f636abca9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='detail-control']/span[2]/button</value>
      <webElementGuid>9a8a6a82-3d95-4df5-9be7-a07f9a52aa1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Piezas'])[1]/following::button[1]</value>
      <webElementGuid>76165cb3-e8f6-4352-abc6-70e3d2e394b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$77.00 M.N. pieza'])[1]/following::button[1]</value>
      <webElementGuid>9d81bed7-8fe2-429e-8e5e-29945eb830d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Agregar'])[1]/preceding::button[1]</value>
      <webElementGuid>c40f7bb7-3efa-4b5f-8132-213983500d16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Detalle'])[1]/preceding::button[1]</value>
      <webElementGuid>4cd1845c-1357-449e-912d-edc1acd826c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/button</value>
      <webElementGuid>011458e6-17c0-42c3-8478-5aea45c1cf13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'addShopCartDetail' and @type = 'button' and @title = 'Agregar a carrito']</value>
      <webElementGuid>ec32705e-420a-48d1-b232-a1ff1311b745</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
