<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_x (1)</name>
   <tag></tag>
   <elementGuidId>36f43681-beaa-41d1-bf87-050b9a3c1ded</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#close_modal_dir</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='close_modal_dir']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b159308d-cbd9-4eec-b625-4096aa1b0e72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>close_modal_dir</value>
      <webElementGuid>c59f459e-9b62-45e1-bf02-c595df744ee5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7dc1d462-40b7-4b13-abd0-adec05a9d91a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn close-modal</value>
      <webElementGuid>5e4c4f04-bc4a-43d7-8e22-b0f3b4342dd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dismiss</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>1c3d6a1e-250e-40b1-bfd7-39a716af5327</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Close</value>
      <webElementGuid>5f63815a-a75d-4053-9310-21f4b2f0bc66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>dismissNewAddressModal()</value>
      <webElementGuid>ffa62eae-fe87-4de5-b955-9b9547c41edd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>x</value>
      <webElementGuid>f07fc97e-8b4e-489d-97b3-e7aa9f2a65c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;close_modal_dir&quot;)</value>
      <webElementGuid>03c60b0c-7642-47d1-8c18-5ed16b68e96f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='close_modal_dir']</value>
      <webElementGuid>d259689c-0713-4810-a292-8f8c90f48bbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal_nuevadireccion']/div/div/div/button</value>
      <webElementGuid>251a78e8-c7aa-49f7-b8f8-e071d963cefe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nueva dirección'])[1]/preceding::button[1]</value>
      <webElementGuid>d2465f39-d479-4fc5-8cd2-511c3482236b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mi dirección'])[1]/preceding::button[1]</value>
      <webElementGuid>47bbf5c0-6345-4764-a18e-fb4f68aa48ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='x']/parent::*</value>
      <webElementGuid>b99b8253-8f24-4bf4-99d5-663c126f1bd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>de45c78e-6a24-4600-8bf4-edc64a8c08c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'close_modal_dir' and @type = 'button' and (text() = 'x' or . = 'x')]</value>
      <webElementGuid>b33bd8fb-1846-4162-9bf6-9d2df314b76f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
