<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_GUARDAR</name>
   <tag></tag>
   <elementGuidId>5fed141b-00f5-47e4-ae6b-5ab1caaa22b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-tertiary.btn-block.btn-lg</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='modal_nuevadireccion']/div/div/div[2]/form/div[3]/div[3]/div[2]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c64106bf-29ca-4920-9be1-be227bde4846</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-disabled</name>
      <type>Main</type>
      <value>restAcc</value>
      <webElementGuid>9b769027-c449-4021-a604-81fe1ddb3fed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-click</name>
      <type>Main</type>
      <value>guardarDireccion();dataLayer.push({'event': 'View Zipcode Modal'});dataLayer.push({'event': 'View Select Colonia'});</value>
      <webElementGuid>7e300f4f-09ca-4b66-b155-d9152e4c8aad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-tertiary btn-block btn-lg</value>
      <webElementGuid>7b603bd3-30ad-494e-9430-1caceaa8f876</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>GUARDAR</value>
      <webElementGuid>911c2327-e533-4860-9348-767c26d59fac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal_nuevadireccion&quot;)/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body ng-scope&quot;]/form[@class=&quot;ng-valid-maxlength ng-valid-minlength ng-dirty ng-valid-parse ng-valid-pattern ng-valid-nombre-direccion-exist ng-valid ng-valid-required&quot;]/div[3]/div[@class=&quot;row mt-25&quot;]/div[@class=&quot;col-xs-12 col-md-6&quot;]/button[@class=&quot;btn btn-tertiary btn-block btn-lg&quot;]</value>
      <webElementGuid>e56282d0-4082-4fea-bf8e-f031a213b380</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal_nuevadireccion']/div/div/div[2]/form/div[3]/div[3]/div[2]/button</value>
      <webElementGuid>e67df5b0-2fc9-47b9-b65b-7883212544e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='REGRESAR'])[1]/following::button[1]</value>
      <webElementGuid>4c6d04f0-d8eb-47d7-8744-381ccfdc273c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='El campo no permite caracteres especiales.'])[5]/following::button[2]</value>
      <webElementGuid>e37f603b-0fba-465d-acf1-4bf8f21356d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='x'])[2]/preceding::button[1]</value>
      <webElementGuid>9f0b276d-5589-4d3b-a869-7f99d90f700d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mi carrito'])[1]/preceding::button[2]</value>
      <webElementGuid>ea2b80d5-6c02-424c-a10a-bd1740a342cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='GUARDAR']/parent::*</value>
      <webElementGuid>052adaea-e36e-49cd-9707-866391533622</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/div[2]/button</value>
      <webElementGuid>3fe936b2-1868-4bb2-83e3-6265368d6f14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'GUARDAR' or . = 'GUARDAR')]</value>
      <webElementGuid>041616b9-c822-4e81-88b3-0a0e5b31b610</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
