<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Resultados de tu bsqueda_btn_addtoCa_d084b1</name>
   <tag></tag>
   <elementGuidId>89dec829-78ae-4d36-9a19-47f7b0378991</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn_addtoCart_7502223772250</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn_addtoCart_7502223772250']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8f1124d1-6378-4334-a60a-a00bb43f0601</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tipocart</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>234df932-2aab-4f78-8382-e765631d51f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>prod</name>
      <type>Main</type>
      <value>prod</value>
      <webElementGuid>9e709cd5-7cac-416d-ab42-2db41b9a8dcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-cart btn-primary ng-scope</value>
      <webElementGuid>bc30570e-aaae-42ac-a46c-d89ca108e29d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tooltip</value>
      <webElementGuid>484b0ce6-2cae-4a63-85a7-34fc0a195262</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>!prod.isArtResurtido</value>
      <webElementGuid>728e77f1-1ba7-4669-9d99-0cd423ad9cc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Agregar a carrito</value>
      <webElementGuid>1400d178-567b-4095-b610-051a0e9de676</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_addtoCart_7502223772250</value>
      <webElementGuid>113683aa-b404-4373-94b1-133ad4467251</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_addtoCart_7502223772250&quot;)</value>
      <webElementGuid>dc7cb664-ce36-470b-8843-78bf5dc46ece</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btn_addtoCart_7502223772250']</value>
      <webElementGuid>b7cec35d-066d-4bd6-88f7-bd8b82bd4727</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='right_control']/button</value>
      <webElementGuid>dd65de1e-25fd-405e-a610-7fe35bc4c30c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>84bc2840-5007-4936-a3c1-feb328b102f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@title = 'Agregar a carrito' and @id = 'btn_addtoCart_7502223772250']</value>
      <webElementGuid>7e4e79c0-e56c-439d-847c-1681952d30bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
