<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Resultados de tu bsqueda_li_prod_mosaic</name>
   <tag></tag>
   <elementGuidId>6c3b4253-9ed0-49a1-bae7-ff96dd5abbe1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.li_prod_mosaic</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='product_list']/div/div[2]/div/div/div/div/div/div/div/a/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>7042f767-c75f-4f0a-8a82-8128de294003</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>li_prod_mosaic</value>
      <webElementGuid>0d92ce9a-3d50-4e63-8b94-e8d93afb192e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-src</name>
      <type>Main</type>
      <value>https://www.lacomer.com.mx/superc/img_art/7501025403058_1.jpg</value>
      <webElementGuid>69fcb2e3-4dc4-43b6-8be9-516b075e6d3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>-articulo-Limpiador Multiusos Desinfectante</value>
      <webElementGuid>dc704240-1679-4f9a-b9d6-02d91c5b1852</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.lacomer.com.mx/superc/img_art/7501025403058_1.jpg</value>
      <webElementGuid>acef2bef-f110-4259-96b3-8232898da1f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product_list&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;ul_prod_product&quot;]/div[@class=&quot;row ul_prod ng-scope&quot;]/div[@class=&quot;categoryProduct xsResponse clearfix&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;col-xs-6 col-sm-4 col-md-3 col-lg-n5 li_prod li_mosaic ng-scope&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;li_prod_picture ng-scope&quot;]/div[@class=&quot;li_prod_image&quot;]/a[1]/div[@class=&quot;middle-cont&quot;]/div[@class=&quot;middle-in horizontal-align&quot;]/img[@class=&quot;li_prod_mosaic&quot;]</value>
      <webElementGuid>7366a153-553f-4bf8-aace-0f64727a15ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='product_list']/div/div[2]/div/div/div/div/div/div/div/a/div/div/img</value>
      <webElementGuid>cc0e4e80-1392-4d28-bae8-e5d71c770d42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='-articulo-Limpiador Multiusos Desinfectante']</value>
      <webElementGuid>f5cb19db-992c-456d-b56c-f01536e01103</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a/div/div/img</value>
      <webElementGuid>949e5662-5cc5-41f8-bc60-82d3f585c2d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = '-articulo-Limpiador Multiusos Desinfectante' and @src = 'https://www.lacomer.com.mx/superc/img_art/7501025403058_1.jpg']</value>
      <webElementGuid>194b3339-6b5b-46b4-8b8c-310e728d425a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
