<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Salir_carritoH</name>
   <tag></tag>
   <elementGuidId>6aac40a9-731e-41f6-9767-e15349f76765</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#carritoH</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='carritoH']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>f3017187-7a39-4737-abee-ece571cb8e3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>carritoH</value>
      <webElementGuid>de680aed-5d3a-44c2-96ae-b5d452d55dc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Mi carrito</value>
      <webElementGuid>5ad4715a-b55b-498e-b354-7162c8f64d2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-src</name>
      <type>Main</type>
      <value>/lacomer/assets/images/lacomer/carrito.png</value>
      <webElementGuid>4c5a6de8-3e02-45d8-8cdd-22d73c15dc06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/lacomer/assets/images/lacomer/carrito.png</value>
      <webElementGuid>b894be37-61b8-4c13-a65d-acb217f02a7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;carritoH&quot;)</value>
      <webElementGuid>ce3bce82-16ad-4912-8eb5-86adb33a881b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='carritoH']</value>
      <webElementGuid>a529b50f-7648-46cf-9df4-4069a6fd920c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header']/div/div/div/ng-template/login-header/div/div/div[2]/div/div/a/img</value>
      <webElementGuid>8be2752e-0c80-4668-b0a0-08c16f58436c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Mi carrito'])[2]</value>
      <webElementGuid>6a3034d3-3b9f-4cd7-a87f-83b4c78f6c85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/a/img</value>
      <webElementGuid>3f959c86-3235-4056-a81c-02ebb6f7e519</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'carritoH' and @alt = 'Mi carrito' and @src = '/lacomer/assets/images/lacomer/carrito.png']</value>
      <webElementGuid>117b8f96-d83a-4303-9399-e6ef3a9fd618</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
