<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Agregaste al carrito 1 pieza de Aceite _698e96</name>
   <tag></tag>
   <elementGuidId>fa9e0338-11d0-40b1-ae16-99fe32f1bea3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.img-responsive</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='logo']/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>d1c9007a-eaaa-41c9-ac6f-eb01a7716738</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-responsive</value>
      <webElementGuid>e1539029-1d70-42be-b40f-720609fd0774</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-src</name>
      <type>Main</type>
      <value>/lacomer/assets/images/lacomer/logo.png</value>
      <webElementGuid>2a0717e7-589b-4977-88bb-e07d7ca4d5ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>LaComer</value>
      <webElementGuid>3c6e93af-a21b-42c6-a7a2-78fcf78f0f54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/lacomer/assets/images/lacomer/logo.png</value>
      <webElementGuid>a54b0c5b-9254-45cc-9b0b-3652bcfe506b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;logo&quot;)/a[@class=&quot;img-responsive&quot;]/img[@class=&quot;img-responsive&quot;]</value>
      <webElementGuid>ff57e909-02a3-4177-b3ac-e839df538a8c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='logo']/a/img</value>
      <webElementGuid>f8762dba-c9f7-4f57-84a0-fc67f414da49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='LaComer']</value>
      <webElementGuid>9205d291-0c4a-491e-8b9b-a16bc5ad57a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>5a4e341f-2810-4f41-8d85-0c1a7f643979</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'LaComer' and @src = '/lacomer/assets/images/lacomer/logo.png']</value>
      <webElementGuid>5458a810-324e-4719-8d2d-187b53a2ecec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
