<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Salir_carritoH_1</name>
   <tag></tag>
   <elementGuidId>9102665d-856c-4967-8b80-698878791f7f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#carritoH</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='carritoH']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>cecb4be7-c018-4b22-be1e-529a511dd6af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>carritoH</value>
      <webElementGuid>cd3cee89-b84d-4362-acb8-2a8e27ae80ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Mi carrito</value>
      <webElementGuid>a0d7d542-b880-4fc8-81ff-a742a3058cc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-src</name>
      <type>Main</type>
      <value>/lacomer/assets/images/lacomer/carrito.png</value>
      <webElementGuid>70f906d1-5918-4f99-81ee-1069b49be8f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>assets/images/lacomer/carrito.png</value>
      <webElementGuid>39afeb0f-254d-4594-b12e-20d427425835</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;carritoH&quot;)</value>
      <webElementGuid>25a73d35-7f6b-4af1-ac3a-36c9591815e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='carritoH']</value>
      <webElementGuid>82307548-c37e-47d5-a7bc-041ff038bd35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header']/div/div/div/ng-template/login-header/div/div/div[2]/div/div/a/img</value>
      <webElementGuid>540661aa-2080-4237-bb0f-2b02da273248</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Mi carrito'])[2]</value>
      <webElementGuid>c04b4258-d4b2-4b85-be69-fbd5c50a0c2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/a/img</value>
      <webElementGuid>93881bf3-901e-4a53-bad0-b3a48493a4b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'carritoH' and @alt = 'Mi carrito' and @src = 'assets/images/lacomer/carrito.png']</value>
      <webElementGuid>12aea1fe-168e-4a9e-8ce0-c9f0f034d082</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
