<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_77.00 M.N. pieza_pediCant</name>
   <tag></tag>
   <elementGuidId>a1fbe0b2-8a3e-40e6-a428-08905cc3ec75</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pediCant</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pediCant']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>42343cb9-ae8d-419a-8b37-d586ba9db3a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0169c2a2-2f4e-4506-a658-4b88f418caae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control pd-input ng-pristine ng-untouched ng-valid ng-empty</value>
      <webElementGuid>228009fa-1827-4864-9249-9cc0c6af43cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pediCant</value>
      <webElementGuid>b50bd162-58b4-4763-b506-08b61def3ebe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pediCant</value>
      <webElementGuid>8eafb305-fd57-4cf7-a8ab-bf9ecf8a2826</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>valueSelected</value>
      <webElementGuid>9d900c19-9fcb-4dda-937e-882b014285f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-keyup</name>
      <type>Main</type>
      <value>AgregarCarritoFromDetalleEnter($event);</value>
      <webElementGuid>12edd3d9-33c2-4b66-b4f0-6d7c367438f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>isgranelpz</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c1a111c2-eba1-42cc-99d6-3feb6e7d233e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pediCant&quot;)</value>
      <webElementGuid>42f3dc19-34b4-44b2-8fbc-4150896b0d1c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pediCant']</value>
      <webElementGuid>f6ae21e3-c5b2-4ee8-bedf-fc44c3a208c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='detail-control']/span/input</value>
      <webElementGuid>b0d3b8db-5f6c-4241-82dd-f121c310997b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>e5678b36-da56-4130-a881-0e9c352937d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'pediCant' and @id = 'pediCant']</value>
      <webElementGuid>480558f2-4063-435d-a9eb-5d34c6a56b1c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
