<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_LaComer Login_j_username</name>
   <tag></tag>
   <elementGuidId>45a6ac49-f53d-4736-8d58-337ae6872f59</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#login-user</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='login-user']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0b22fb75-c7a8-4ecd-9db6-236ad7690d1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>j_username</value>
      <webElementGuid>b0cddf82-d24b-4997-80ca-2af1bd20fe65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>login-user</value>
      <webElementGuid>bdf4857e-1958-4885-bc72-1c843bc1e560</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input ng-pristine ng-empty ng-valid-maxlength ng-valid ng-valid-required ng-touched</value>
      <webElementGuid>398d9d7c-a6ae-4ba8-b906-c87b9c57a354</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>f66c71da-3315-4428-83e7-428c8c31df72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Introducir correo electrónico*</value>
      <webElementGuid>9835b21a-784f-48ee-8757-43ef4021835e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7273e694-e4d0-46c6-8fd4-c90861685f60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>932e4b68-428e-4fbd-abf3-74686f8aff1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>313e312c-9bad-45c7-a7cb-dfa386b2f4d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-model</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>52b0033f-fac9-4415-9e59-5d0a3d6d8748</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-keypress</name>
      <type>Main</type>
      <value>validateLoginEnter($event);</value>
      <webElementGuid>7ad2e27d-ae05-4e86-9b95-8763e0399d87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login-user&quot;)</value>
      <webElementGuid>f41ad847-4927-4b86-aa81-ddd9f7d3dab4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='login-user']</value>
      <webElementGuid>2cb8885b-1520-4e12-abc5-36f440222da3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='login-form']/div/form/div/div/div/div/div/input</value>
      <webElementGuid>5eb528b8-bda5-436f-a743-5fdd4fe22360</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/div/div/input</value>
      <webElementGuid>c5b34302-7d6c-48f4-ae5f-d91f9e2a6fdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'j_username' and @id = 'login-user' and @placeholder = 'Introducir correo electrónico*' and @type = 'text']</value>
      <webElementGuid>0ae9109a-b9a6-4d1a-8aef-44197c92a51b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
