<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Agregaste al carrito 1 pieza de Aceit_9b1229</name>
   <tag></tag>
   <elementGuidId>18b8f2b2-f114-4edd-938f-aca714ba623c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#idSearch</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='idSearch']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>65f640ee-a9bb-45e6-9cf8-6b3edc94b32e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Busca uno o más productos, separándolos por coma</value>
      <webElementGuid>6db0caf0-7682-4d54-9ee2-26795be416ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>63b8fe0f-9950-4416-b933-2608580c9084</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>idSearch</value>
      <webElementGuid>97f31bdc-281f-41c4-97b5-560615475ef2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-value</name>
      <type>Main</type>
      <value>criterio</value>
      <webElementGuid>19daae1a-024a-445e-ac68-bdf412059924</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>search form-control ng-pristine ng-untouched ng-valid ng-not-empty ng-dirty-add ng-valid-parse-add</value>
      <webElementGuid>01d0e969-3c55-463d-a78f-c2ae7ba28bcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>termino</value>
      <webElementGuid>452c18b4-4c6d-4651-a418-9313a478f721</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a79688cb-fd0e-4553-bb60-2c2482f7b505</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-focus</name>
      <type>Main</type>
      <value>onFocusSearch()</value>
      <webElementGuid>9385206e-11d4-42a9-a51b-a4d4ab3cbab0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>updateSuggestions()</value>
      <webElementGuid>afeb6c71-e6d1-47f8-b816-345312be2b6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-entersuggestion</name>
      <type>Main</type>
      <value>searchSugres(liselectedtext)</value>
      <webElementGuid>10180561-ff13-43b2-a303-7e74f3f3ef3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Aceite Canola</value>
      <webElementGuid>96ee5298-5bf3-4835-8eb9-670d1e436ee5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-animate</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>a1ad4b89-ee9f-4b9f-a78e-0831d583f1f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;idSearch&quot;)</value>
      <webElementGuid>dc613b61-a483-4282-8d3a-b583d3bfe3a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='idSearch']</value>
      <webElementGuid>a220f5db-1c7a-4c3d-8aa6-1cd50ba95b39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='search']/div/div/div/input</value>
      <webElementGuid>41338bcc-3335-432d-9be5-df59b8b94dcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//search-bar/div/div/div/div/input</value>
      <webElementGuid>5232ea10-0d49-44dc-bfda-07963a7d62f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Busca uno o más productos, separándolos por coma' and @type = 'search' and @id = 'idSearch']</value>
      <webElementGuid>73ee198f-6c87-48a6-9872-9f8aead29583</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
