<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Elige un nombre para tu direccin_nombre</name>
   <tag></tag>
   <elementGuidId>e56ec84e-6788-4dea-a919-a96ae15813f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nombre</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nombre']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>714a3d44-cf9c-4bce-81e4-d574752f071c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2ada4475-70c7-432d-ad46-41ff8d42f081</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>e7e1d5b8-f130-44b8-b148-b271918d4c6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>bce1be01-3852-4b45-85d0-c9c52ab2ca0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nombre</value>
      <webElementGuid>1b710873-933f-422a-ab08-67e3883c6ade</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nombre</value>
      <webElementGuid>004b707e-7ade-4536-ae25-5ac78d4a229e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-minlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>3db215ec-2eb5-451a-82bb-75adf1ff8247</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>5d1782f9-8ace-4445-a361-7efc35debffe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-model</name>
      <type>Main</type>
      <value>nombre</value>
      <webElementGuid>8ba4701e-0cda-45e6-97e0-44fe0363055e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ej: Casa, Oficina, etc.</value>
      <webElementGuid>d2d028ca-2986-4ce8-ba71-ba6e3bd28800</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-required</name>
      <type>Main</type>
      <value>isNombreRequired</value>
      <webElementGuid>329b4d0d-2197-4a21-97c8-4c4e1d22d515</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-xs-12 col-md-11 select_nobk ng-pristine ng-invalid ng-invalid-required ng-valid-maxlength ng-valid-minlength ng-untouched ng-empty ng-not-empty-add ng-pristine-remove ng-dirty-add ng-valid-nombre-direccion-exist-add ng-valid-parse-add ng-valid-add ng-invalid-remove ng-valid-required-add ng-invalid-required-remove</value>
      <webElementGuid>56f863f7-e6c3-4e30-aec2-74544ca0b20e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>09b7a326-e8b9-4411-8f4c-32dcd824db10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-animate</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>eca0df66-2237-4a5d-a264-1f437382207c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal_nuevadireccion&quot;)/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body ng-scope&quot;]/form[@class=&quot;ng-invalid ng-invalid-required ng-valid-maxlength ng-valid-minlength ng-dirty ng-valid-parse ng-valid-pattern ng-valid-add ng-invalid-remove ng-valid-required-add ng-invalid-required-remove ng-animate ng-valid-nombre-direccion-exist-add&quot;]/div[3]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12 col-md-7&quot;]/input[@id=&quot;nombre&quot;]</value>
      <webElementGuid>8e51d8a8-6037-41b3-ba58-43b6ddda2a5f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nombre']</value>
      <webElementGuid>c94834a8-a1f2-499a-a7f4-7eff63a2a891</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal_nuevadireccion']/div/div/div[2]/form/div[3]/div[2]/div/input</value>
      <webElementGuid>9e6e687c-d703-4ef1-92e5-efcd589b3a3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/input</value>
      <webElementGuid>09ce03be-d1bf-4608-b476-3334488753e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'nombre' and @name = 'nombre' and @placeholder = 'Ej: Casa, Oficina, etc.']</value>
      <webElementGuid>e47a742e-f316-4a68-a653-705bbfb40223</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
