<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nmero exterior_street_number</name>
   <tag></tag>
   <elementGuidId>e2319f92-1285-419e-a07f-28b0bd5461cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#street_number</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='street_number']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5bac97f7-ae3b-4695-b218-8cb6ba29b001</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f8b922dd-1cee-4c4f-8660-18a185428ae6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>street_number</value>
      <webElementGuid>3f515397-8e8a-4067-b7a6-85a0a6f04a30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>street_number</value>
      <webElementGuid>f70a5ef4-2d73-4a08-be2d-8a72eaf3a284</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-model</name>
      <type>Main</type>
      <value>street_number</value>
      <webElementGuid>7c257541-f1c1-4056-8283-266b18cec158</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>5d53d743-b444-4ef6-aa20-cf44510a2b36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-pattern</name>
      <type>Main</type>
      <value>/^[0-9A-Za-z -]{1,5}$/i</value>
      <webElementGuid>e58200e2-3f45-42f3-aa80-e7317aa866b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-blur</name>
      <type>Main</type>
      <value>isValidFormDirection();</value>
      <webElementGuid>85f42515-5cd4-448c-8966-e765fdfb1c1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-maxlength</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>2ef48ee0-ef2e-472c-9a5b-5988ceac5fee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-xs-12 select_nobk ng-pristine ng-invalid ng-invalid-required ng-valid-maxlength ng-valid-pattern ng-untouched ng-empty ng-not-empty-add ng-pristine-remove ng-dirty-add ng-valid-parse-add ng-valid-add ng-invalid-remove ng-valid-required-add ng-invalid-required-remove ng-animate ng-empty-remove</value>
      <webElementGuid>9d224999-dcd5-4eb8-9cb5-90660add9fa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-animate</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>39e9239f-3d47-4884-bef3-f6978f5c6e3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;street_number&quot;)</value>
      <webElementGuid>eb1a85b1-b093-4148-8bd1-8d30923efdfc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='street_number']</value>
      <webElementGuid>674a5f75-7ca9-451a-a43d-efaa3cf222b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal_nuevadireccion']/div/div/div[2]/form/div[2]/div/div[2]/div/input</value>
      <webElementGuid>50a5a2ea-dc8d-4f86-91ec-c3d8519b70d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>b2b2025a-9388-426e-9315-3908797c5f3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'street_number' and @name = 'street_number']</value>
      <webElementGuid>cdd96f86-f7f0-4960-a642-0a077f251ecf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
