<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Cdigo Postal_postal_code</name>
   <tag></tag>
   <elementGuidId>47537078-1615-43c4-9912-279e7e36cd2b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#postal_code</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='postal_code']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>38eaf0e3-2384-4867-9369-3ca447f9d3a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>postal_code</value>
      <webElementGuid>f382fe2d-a70b-46b5-bb82-93a6b950d4d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>postal_code</value>
      <webElementGuid>e91179ac-0a15-4fa8-8b89-6de797eac5e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-model</name>
      <type>Main</type>
      <value>postal_code</value>
      <webElementGuid>98667adc-78bb-486b-bf7c-8e4ac9f801d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>1354ba4f-0249-489a-818c-986ef261c2df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-change</name>
      <type>Main</type>
      <value>resetLatLong();buscarColonias();</value>
      <webElementGuid>b5b7d8d6-456d-44bb-90df-b8d01cefa22f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-maxlength</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>384c4e3b-7e8f-4fb2-b0d0-82e5b8b00bad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-minlegth</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>7dd1d508-c1c6-4710-abe4-9ea474ee5ae7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-pattern</name>
      <type>Main</type>
      <value>/^[0-9]{4,5}$/i</value>
      <webElementGuid>4d276d43-efcc-4634-bd68-c784722ad97a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>numbers-only</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a407fe31-81f4-4da5-a492-da3a87eba403</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-xs-12 col-md-12 select_nobk ng-pristine ng-invalid ng-invalid-required ng-valid-pattern ng-empty ng-valid-maxlength ng-touched</value>
      <webElementGuid>9ad667ad-7bfa-4aa9-8509-486a0a222477</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;postal_code&quot;)</value>
      <webElementGuid>b70b2fa4-daf9-4135-be39-05ba349e6936</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='postal_code']</value>
      <webElementGuid>53261d9e-5675-4e53-b071-6cd86120226a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal_nuevadireccion']/div/div/div[2]/form/div[2]/div/div[2]/div[3]/input</value>
      <webElementGuid>7379e9b6-b564-4482-baeb-dca5ce4b308a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>edca5b19-c401-46d9-9e49-b04367127e75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'postal_code' and @name = 'postal_code']</value>
      <webElementGuid>e2f30960-e2e4-4134-b2d5-27eae41329f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
