<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_BUSCAR PRODUCTOS_idSearch</name>
   <tag></tag>
   <elementGuidId>c74461e3-0850-45a1-823a-23cfc3d98cec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#idSearch</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='idSearch']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0658e130-1a6a-4049-a49f-98691189b971</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Busca uno o más productos, separándolos por coma</value>
      <webElementGuid>9c760195-ea15-4824-b6b8-cbb23597a25a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>18d1ebc8-9c77-45b7-818f-f59d2c5023eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>idSearch</value>
      <webElementGuid>73139026-cb0a-499f-8f55-1f5ab79f448e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-value</name>
      <type>Main</type>
      <value>criterio</value>
      <webElementGuid>108e5dac-97d4-4fbd-b37d-2a0c0083947f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>search form-control ng-pristine ng-untouched ng-valid ng-empty ng-not-empty-add ng-pristine-remove ng-dirty-add ng-valid-parse-add</value>
      <webElementGuid>56ec31ba-42e7-42d9-acd5-bf25269eb296</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>termino</value>
      <webElementGuid>42adc18b-5afc-4b89-be19-0f22c0bfc315</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d65b0c20-3d5b-431d-b508-4deb14d5725e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-focus</name>
      <type>Main</type>
      <value>onFocusSearch()</value>
      <webElementGuid>a61714c4-6992-40be-bfd8-02f65f6b6f5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>updateSuggestions()</value>
      <webElementGuid>fd708f7a-e9b7-4428-a7b3-1b56fa839070</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-entersuggestion</name>
      <type>Main</type>
      <value>searchSugres(liselectedtext)</value>
      <webElementGuid>da7c9238-69a1-4fff-885b-e50be086725f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-animate</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>1784a835-f24c-4f4e-9f03-25a1a80bee0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;idSearch&quot;)</value>
      <webElementGuid>170e3c28-21d1-4b85-881e-1e859e6a9456</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='idSearch']</value>
      <webElementGuid>6daf493f-1d3f-4d5d-a7e5-58de710dbe69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='search']/div/div/div/input</value>
      <webElementGuid>28636720-2b31-4056-8592-1b04ae58800f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//search-bar/div/div/div/div/input</value>
      <webElementGuid>905465b0-ec9c-49f5-bab9-67ff92297a7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Busca uno o más productos, separándolos por coma' and @type = 'search' and @id = 'idSearch']</value>
      <webElementGuid>0231a30f-bcb8-4e5f-98b2-fae415b832c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
