<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Calle_route</name>
   <tag></tag>
   <elementGuidId>f5d71794-a1b6-495e-b343-fcc7403959a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#route</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='route']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3a622774-4794-49af-9fb9-660ad47d9c5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6186218f-dbeb-4343-8d9f-ebb015f4f67c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-xs-12 col-md-12 select_nobk ng-pristine ng-invalid ng-invalid-required ng-valid-maxlength ng-valid-pattern ng-untouched ng-empty</value>
      <webElementGuid>ca7f5750-dc87-4a16-b549-ae330a21c159</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>route</value>
      <webElementGuid>ffdc99b5-101b-49f6-9409-60f88b36fccb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>route</value>
      <webElementGuid>459dcca5-8fe2-477a-8b7f-1ecf83d8ae4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-maxlength</name>
      <type>Main</type>
      <value>80</value>
      <webElementGuid>8ce8dacb-4b86-4484-b288-021415ab3741</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-model</name>
      <type>Main</type>
      <value>route</value>
      <webElementGuid>512f938f-4617-4036-8150-9c091e63ef10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>80</value>
      <webElementGuid>9fcef7d3-387d-4719-a6f8-8ff5874fdb6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-pattern</name>
      <type>Main</type>
      <value>/^[0-9A-Za-z,. ñáéíóú ÑÁÉÍÓÚ -]{1,80}$/</value>
      <webElementGuid>6ab82d22-563a-49d8-b2aa-e9af3dd6b6d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return validaCaracteresParaDirCheck(event);</value>
      <webElementGuid>7268c0f5-edd5-45d4-b321-c34a6ebb03cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-blur</name>
      <type>Main</type>
      <value>isValidFormDirection();</value>
      <webElementGuid>a6c24612-df6e-4f5a-a59a-bf3cc8811b0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;route&quot;)</value>
      <webElementGuid>40414e5c-1ac4-4912-a0d1-012a3f7226c0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='route']</value>
      <webElementGuid>13e30b28-6db9-4387-9502-45bf332dcc4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal_nuevadireccion']/div/div/div[2]/form/div[2]/div/div/div/input</value>
      <webElementGuid>def11bfa-4220-497d-a29f-b8d25595d5f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>df0061e2-c55d-4733-8845-64b32cbc6e0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'route' and @name = 'route']</value>
      <webElementGuid>1b1a6fbc-1379-497b-b53e-3d29d38bdb09</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
