<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Quin recibe_nom_recibe</name>
   <tag></tag>
   <elementGuidId>89e9eae4-421e-45ab-b288-432b6d21a939</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nom_recibe</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nom_recibe']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>22e72531-e7da-4f8d-92e1-f529e9d62d00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>893a66b6-eff9-43d0-a066-e880ae30f283</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nom_recibe</value>
      <webElementGuid>55013465-b929-4b09-89a0-5b500427f4c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>05d787b8-ac20-4ae1-a463-3ae65c88fda8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>f4ccbdc3-4c5e-4912-9298-271a3e492520</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nom_recibe</value>
      <webElementGuid>f5dd76c1-3127-48c1-9c14-dcd64ae06d4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>a8ae67bf-e263-4eb6-a320-0f9e3140ec68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-model</name>
      <type>Main</type>
      <value>nom_recibe</value>
      <webElementGuid>ad1dda65-f67d-4df6-a6c3-60f658105d37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-xs-12 col-md-10 select_nobk  ng-pristine ng-untouched ng-valid ng-empty ng-valid-maxlength</value>
      <webElementGuid>8becab04-9890-4b71-ba48-dcf9b4d035e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nom_recibe&quot;)</value>
      <webElementGuid>ea8ce8e2-7aed-4f53-8c41-b03df734921f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nom_recibe']</value>
      <webElementGuid>4c2b49d1-bf84-438f-a138-b4a2df2800ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal_nuevadireccion']/div/div/div[2]/form/div[3]/div[2]/div[2]/input</value>
      <webElementGuid>5a4296c6-11aa-4aaf-9320-3207d0c12a62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div[2]/input</value>
      <webElementGuid>f6cab2c3-30f2-4e32-a0f9-f5bd1ea21c17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'nom_recibe' and @id = 'nom_recibe']</value>
      <webElementGuid>7753047d-bd27-4a0b-8df2-6f1d66df6a75</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
