<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Ingresa</name>
   <tag></tag>
   <elementGuidId>428dcc11-ad74-4ee7-9431-68a60d9c33a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lnkLogin > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='lnkLogin']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>31a7243e-b069-4ea9-8e76-b7eaa4746de2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ingresa</value>
      <webElementGuid>f8d3004b-ff3b-4e37-9765-b930b0cea279</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lnkLogin&quot;)/span[1]</value>
      <webElementGuid>a1af23c9-7b0d-48c8-9552-eb89b64152ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='lnkLogin']/span</value>
      <webElementGuid>29ceb8d5-869c-4ba4-a2e0-dc4f5b342b58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BUSCAR PRODUCTOS'])[1]/following::span[1]</value>
      <webElementGuid>b505fbf4-b974-4a43-a6f9-7a30620f21ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$0 M.N'])[1]/preceding::span[1]</value>
      <webElementGuid>7e7735c4-8438-4bf1-a917-10cf2f0e55c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Estás en: La Comer Coyoacán'])[1]/preceding::span[2]</value>
      <webElementGuid>e4fa62fb-3b5f-48a2-8aac-427c968ded87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ingresa']/parent::*</value>
      <webElementGuid>5eadc1e5-b978-4403-b4bf-2c4fd92987e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/span</value>
      <webElementGuid>1291cebb-8340-4890-8d6d-58c5cf995e18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Ingresa' or . = 'Ingresa')]</value>
      <webElementGuid>54599420-7a6b-4d9b-a05a-2716cbbea59d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
