<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Instrucciones de entrega_entrega</name>
   <tag></tag>
   <elementGuidId>f32f652e-903b-4c66-8ff0-efec701cd8ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#entrega</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='entrega']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>3b24f7d9-be3d-4712-b76d-c659175d5011</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>80</value>
      <webElementGuid>60518475-d6c0-439e-bdce-126cda0b7735</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-xs-12 select_nobk ng-pristine ng-valid ng-untouched ng-empty ng-valid-maxlength ng-not-empty-add ng-pristine-remove ng-dirty-add ng-valid-parse-add ng-animate ng-empty-remove</value>
      <webElementGuid>31487a62-e4b4-4027-915e-b59a7175a40c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>entrega</value>
      <webElementGuid>05adc9cb-19f2-411a-992b-bbde94a7d176</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>entrega</value>
      <webElementGuid>bc298818-236a-4fb3-b7ba-ae4813bacb2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-model</name>
      <type>Main</type>
      <value>entrega</value>
      <webElementGuid>f4d5cb4d-add0-4e04-b6f8-139f75861351</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>1931cdd0-b840-4d26-bdb5-8bfd4c2e274f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>0e59d330-b1ff-4dd7-bdf2-09fde8c04c10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ej.: Entregar en cajas, dejar con el portero...</value>
      <webElementGuid>7f745d8e-367f-4b15-bc18-d5c50299c9ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-animate</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>68bb962a-a889-419f-9e28-9bf26b53a7d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;entrega&quot;)</value>
      <webElementGuid>d0313c19-d3c7-432d-8d8d-4cc72f8cdd20</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='entrega']</value>
      <webElementGuid>c7341542-36e4-4b90-822f-e5a1709ee41e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal_nuevadireccion']/div/div/div[2]/form/div[3]/div[2]/div[3]/textarea</value>
      <webElementGuid>0073d51c-850f-45c1-a28d-a46f1b19ba15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>9c1f60a2-317b-4b4a-a8dd-a4e971e0dbfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'entrega' and @name = 'entrega' and @placeholder = 'Ej.: Entregar en cajas, dejar con el portero...']</value>
      <webElementGuid>4140d3b4-e400-4186-baac-2f5c0397c82c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
